import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalProvider from "./context/globalprovider";
import { ThemeProvider } from "./context/themeprovdier";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
      suppressHydrationWarning // 👈 Added this to stop the hydration error trace
    >
      <body className="min-h-full flex flex-col font-inter overflow-x-hidden">
        <ThemeProvider>
          <GlobalProvider>
            {children}
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}